# Generated by Django 4.2 on 2023-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=80)),
                ('country_image', models.ImageField(default='', upload_to='dynamicimage')),
            ],
        ),
    ]
